#!/bin/sh

PYTHON=`which python33`

if [ "x$PYTHON" = "x" ]
then
  PYTHON=`which python3.3`
fi

if [ "x$PYTHON" = "x" ]
then
  PYTHON=`which python3`
fi

if [ "x$PYTHON" = "x" ]
then
  PYTHON=`which python`
fi

DIR=$(dirname $0)
$PYTHON $DIR/recolor.py "$@"
